# Generated by Django 4.1 on 2025-06-28 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crud", "0004_product_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
